# theme = "onedark"

[editor]
shell = ["zsh", "-c"]
auto-save = true
color-modes = true
bufferline = "always"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1
