(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(ac-ispell ace-link aggressive-indent auto-complete auto-highlight-symbol auto-yasnippet blacken ccls centered-cursor-mode clang-format clean-aindent-mode code-cells column-enforce-mode company-anaconda anaconda-mode company-c-headers company-lua company-posframe company-quickhelp company-rtags company-statistics company-ycmd company counsel-projectile counsel cpp-auto-include cython-mode dactyl-mode dap-mode lsp-docker bui yaml define-word devdocs dired-quick-sort disaster drag-stuff dumb-jump editorconfig ef-themes esh-help eshell-prompt-extras eshell-z eval-sexp-fu evil-anzu anzu evil-args evil-cleverparens paredit evil-collection annalist evil-easymotion evil-escape evil-exchange evil-goggles evil-iedit-state iedit evil-indent-plus evil-lion evil-lisp-state evil-matchit evil-nerd-commenter evil-numbers evil-surround evil-textobj-line evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar expand-region eyebrowse fancy-battery fasd flx-ido flx flycheck-pos-tip pos-tip flycheck-rtags flycheck-ycmd flycheck fuzzy gendoxy golden-ratio google-c-style google-translate helm-make help-fns+ hide-comnt highlight-indentation highlight-numbers parent-mode highlight-parentheses hl-todo hungry-delete ibuffer-projectile importmagic epc ctable concurrent indent-guide info+ ivy-avy ivy-hydra ivy-purpose ivy-rtags ivy-xref ivy-yasnippet launchctl link-hint live-py-mode lorem-ipsum lsp-ivy lsp-origami origami lsp-pyright lsp-python-ms lsp-treemacs lsp-ui lsp-mode markdown-mode lua-mode multi-line shut-up multi-term multi-vterm nose open-junk-file org-superstar osx-clipboard osx-trash paradox spinner password-generator persistent-scratch pip-requirements pipenv load-env-vars pippel poetry transient compat popup popwin py-isort pydoc pyenv-mode pythonic f pylookup pytest pyvenv quickrun rainbow-delimiters restart-emacs reveal-in-osx-finder rtags shell-pop smartparens smex space-doc spaceline-all-the-icons memoize spaceline all-the-icons powerline spacemacs-purpose-popwin spacemacs-whitespace-cleanup sphinx-doc srefactor stickyfunc-enhance string-edit-at-point string-inflection swiper ivy symbol-overlay symon term-cursor terminal-here toc-org treemacs-evil treemacs-icons-dired treemacs-persp persp-mode treemacs-projectile treemacs projectile cfrs ht pfuture ace-window avy posframe undo-tree queue unkillable-scratch uuidgen vi-tilde-fringe vim-powerline vimrc-mode volatile-highlights vterm wgrep window-purpose imenu-list winum writeroom-mode visual-fill-column ws-butler xterm-color yaml-mode yapfify yasnippet-snippets yasnippet ycmd pkg-info request-deferred s dash request deferred epl async bind-map diminish dotenv-mode evil-evilified-state font-lock+ holy-mode hybrid-mode evil goto-chg hydra lv pcre2el which-key)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
